name: React Native E2E Tests (Android)

on:
    pull_request:
    push:
        branches: [trunk]

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
    test:
        runs-on: macos-13
        permissions:
            contents: read
        if: false
        #if: ${{ github.repository == 'WordPress/gutenberg' || github.event_name == 'pull_request' }}
        strategy:
            matrix:
                native-test-name: [gutenberg-editor-rendering]
                api-level: [29]

        steps:
            - name: checkout
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
              with:
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
                  persist-credentials: false

            - name: Use desired version of Java
              uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
              with:
                  distribution: 'corretto'
                  java-version: '17'

            - name: Setup Node.js and install dependencies
              uses: ./.github/setup-node

            - name: Restore tests setup cache
              uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
              with:
                  path: |
                      ~/.appium
                  key: ${{ runner.os }}-tests-setup-${{ hashFiles('package-lock.json') }}

            - name: Prepare tests setup
              run: npm run native test:e2e:setup

            - name: Gradle cache
              uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2

            # AVD cache disabled as it caused emulator termination to hang indefinitely.
            # https://github.com/ReactiveCircus/android-emulator-runner/issues/385
            # - name: AVD cache
            #   uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
            #   id: avd-cache
            #   with:
            #       path: |
            #           ~/.android/avd/*
            #           ~/.android/adb*
            #       key: avd-${{ matrix.api-level }}
            #
            # - name: Create AVD and generate snapshot for caching
            #   if: steps.avd-cache.outputs.cache-hit != 'true'
            #   uses: reactivecircus/android-emulator-runner@62dbb605bba737720e10b196cb4220d374026a6d # v2.33.0
            #   with:
            #       api-level: ${{ matrix.api-level }}
            #       force-avd-creation: false
            #       emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
            #       disable-animations: false
            #       arch: x86_64
            #       profile: Nexus 6
            #       script: echo "Generated AVD snapshot for caching."

            - name: Run tests
              uses: reactivecircus/android-emulator-runner@62dbb605bba737720e10b196cb4220d374026a6d # v2.33.0
              env:
                  NATIVE_TEST_NAME: ${{ matrix.native-test-name }}
              with:
                  api-level: ${{ matrix.api-level }}
                  force-avd-creation: false
                  emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
                  disable-animations: true
                  arch: x86_64
                  profile: Nexus 6
                  script: npm run native test:e2e:android:local "$NATIVE_TEST_NAME"

            - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
              if: always()
              with:
                  name: android-screen-recordings
                  path: packages/react-native-editor/android-screen-recordings

            - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
              if: always()
              with:
                  name: appium-logs
                  path: packages/react-native-editor/appium-out.log
