name: React Native E2E Tests (iOS)

on:
    pull_request:
    push:
        branches: [trunk]

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
    test:
        runs-on: macos-13
        permissions:
            contents: read
        if: false
        #if: ${{ github.repository == 'WordPress/gutenberg' || github.event_name == 'pull_request' }}
        strategy:
            matrix:
                xcode: ['14.2']
                device: ['iPhone 14']
                native-test-name: [gutenberg-editor-rendering]

        steps:
            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
              with:
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
                  persist-credentials: false

            - uses: ruby/setup-ruby@1287d2b408066abada82d5ad1c63652e758428d9 # v1.214.0
              with:
                  # `.ruby-version` file location
                  working-directory: packages/react-native-editor/ios

            - name: Switch Xcode version to ${{ matrix.xcode }}
              env:
                  VERSION: ${{ matrix.xcode }}
              run: sudo xcode-select --switch "/Applications/Xcode_${VERSION}.app"

            - name: Launch simulator
              env:
                  DEVICE: ${{ matrix.device }}
              run: (open -a Simulator && xcrun simctl boot "${DEVICE}") &

            - name: Setup Node.js and install dependencies
              uses: ./.github/setup-node

            - name: Restore tests setup cache
              uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
              with:
                  path: |
                      ~/.appium
                  key: ${{ runner.os }}-tests-setup-${{ hashFiles('package-lock.json') }}

            - name: Prepare tests setup
              run: npm run native test:e2e:setup

            - name: Prepare build cache key
              run: find package-lock.json packages/react-native-editor/ios packages/react-native-aztec/ios packages/react-native-bridge/ios -type f -print0 | sort -z | xargs -0 shasum | tee ios-checksums.txt

            - name: Restore build cache
              uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
              with:
                  path: |
                      packages/react-native-editor/ios/build/GutenbergDemo/Build/Products/Release-iphonesimulator/GutenbergDemo.app
                      packages/react-native-editor/ios/build/WDA
                  key: ${{ runner.os }}-ios-build-${{ matrix.xcode }}-${{ matrix.device }}-${{ hashFiles('ios-checksums.txt') }}

            - name: Restore pods cache
              uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
              with:
                  path: |
                      packages/react-native-editor/ios/Pods
                      ~/Library/Caches/CocoaPods
                      ~/.cocoapods/repos/trunk
                      packages/react-native-editor/ios/vendor
                  key: ${{ runner.os }}-pods-${{ hashFiles('packages/react-native-editor/ios/Gemfile.lock') }}-${{ hashFiles('packages/react-native-editor/ios/Podfile.lock') }}-${{ hashFiles('package-lock.json') }}

            - name: Bundle iOS
              run: npm run native test:e2e:bundle:ios

            - name: Build (if needed)
              run: test -e packages/react-native-editor/ios/build/GutenbergDemo/Build/Products/Release-iphonesimulator/GutenbergDemo.app/GutenbergDemo || npm run native test:e2e:build-app:ios

            - name: Build Web Driver Agent (if needed)
              run: test -d packages/react-native-editor/ios/build/WDA || npm run native test:e2e:build-wda

            - name: Run iOS Device Tests
              env:
                  NATIVE_TEST_NAME: ${{ matrix.native-test-name }}
              run: TEST_RN_PLATFORM=ios npm run native device-tests:local "$NATIVE_TEST_NAME"

            - name: Prepare build cache
              run: |
                  rm packages/react-native-editor/ios/build/GutenbergDemo/Build/Products/Release-iphonesimulator/GutenbergDemo.app/main.jsbundle
                  rm -rf packages/react-native-editor/ios/build/GutenbergDemo/Build/Products/Release-iphonesimulator/GutenbergDemo.app/assets

            - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
              if: always()
              with:
                  name: ios-screen-recordings
                  path: packages/react-native-editor/ios-screen-recordings

            - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
              if: always()
              with:
                  name: appium-logs
                  path: packages/react-native-editor/appium-out.log
